class Piece:
	'''
	Base Class for all Pieces. Most methods and attributes go here, and can be overloaded if necessary.
	'''
	...

class Pawn(Piece): ...

class Bishop(Piece): ...

class Knight(Piece): ...

class Rook(Piece): ...

class King(Piece): ...

class Queen(Piece): ...